PDArchiver/urls.py
from django.contrib import admin
from django.urls import path, include
from search.views import searchContextPage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('search/', include('search.urls')),
    path('', searchContextPage.as_view(), name='searchContext'),
]

accounts/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.loginPage.as_view(), name='login'),
    path('register/', views.registerPage.as_view(), name='register'),
    path('profile/', views.profilePage.as_view(), name='myProfile'),
    path('logout/', views.logoutUser, name='logout'),
]

search/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('home/', views.homePage.as_view(), name='search'),
    path('upload/', views.uploadPage.as_view(), name='upload'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, 
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy
from django.utils import timezone

from .managers import PDFUserManager


class Role (models.Model):
    STUDENT = 1
    FACULTY = 2

    ROLE_CHOICES = (
        (STUDENT, 'student'),
        (FACULTY, 'faculty')
    )

    rolesId = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, primary_key=True)

    def __str__(self):
        return self.get_id_display()

# PDF BASE USER: USER MODEL WHICH HANDLES ALL THE MODELS FOR ANY KIND OF USERS.

class PDFBaseUser(AbstractBaseUser, PermissionsMixin):
    userId = models.CharField(max_length=150, unique=True)
    email = models.EmailField(gettext_lazy('email address'), unique=True)
    studentNumber = models.CharField(max_length=7, null=False)
    firstName = models.CharField(max_length=255, null=False)
    middleName = models.CharField(max_length=255)
    lastName = models.CharField(max_length=255, null=False)
    roles = models.ManyToManyField(Role)
    dateJoined = models.DateTimeField(default=timezone.now)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = PDFUserManager()

    USERNAME_FIELD = 'userId'
    REQUIRED_FIELDS = ['email', 'firstName', 'lastName', ]

    def __str__(self):
        return self.userId

    def detailName(self):
        return self.firstName + ' ' + self.lastName

    def as_dict(self):
        context = {
            'id' : self.id,
            'fullName' : self.firstName + ' ' + self.lastName,
        }
        return context

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import PDFBaseUser
from .form import RegisterForm,LoginForm
# Create your views here.

class loginPage(View):
    def get(self, request, *args, **kwargs):
        form = LoginForm()
        if request.user.is_authenticated:
            return redirect('search:home')
        else:
            context = {
                'form' : form,
            }
            return render(request, template_name='loginPage.html', context=context)

    def post(self, request, *args, **kwargs):

        form = LoginForm(request.POST)

        if form.is_valid():
            userId = form.cleaned_data['userId']
            studentNumber = form.cleaned_data['studentNumber']
            password = form.cleaned_data['password']
            user = authenticate(request, username=userId, password=password)
        else:
            userId = form.cleaned_data['userId']
            password = form.cleaned_data['password']
            user = authenticate(request, username=userId, password=password)
            

        if user is not None:
            login(request, user)
            return redirect('/search/home')
        else:
            messages.error(request, "Incorrect User ID or Password, please try again.")
            print('User is incorrect')
        context={
            'form' : form,
        }
        return render(request, template_name='loginPage.html', context=context)


class registerPage(View):
    def get(self, request, *args, **kwargs):
        form = RegisterForm()
        
        context = {
            'form' : form,
        }

        return render(request, template_name='registerPage.html', context=context)
    
    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)
        if form.is_valid():            
            firstName = form.cleaned_data['firstName']
            lastName = form.cleaned_data['lastName']
            email = form.cleaned_data['email']
            studentNumber = form.cleaned_data['studentNumber']

            try:
                user = form.save()
                messages.success(request, "Account has been created!")
                return redirect('login')
            except:
                messages.error(request, "User already exists")
                return redirect('login')
            
        context = {
            'form' : form
        }

        return render(request, template_name='registerPage.html', context=context)

class profilePage(View):

    def get(self, request, *args, **kwargs):

        context = {
            
        }

        return render (request,template_name='profilePage.html', context=context)


@login_required(login_url='/')
def logoutUser(request):
    logout(request)
    return redirect('/')

accounts/templates/loginPage.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="loginPage">
	<div class="loginPageWrapper">
		<div class="loginPageWrapperHeader">
			<h4>PD DOCUMENTS ARCHIVER</h4>
		</div>
		<div class="loginMainScreen">
			<div class="loginPageImage">
				<img src="{% static 'img/login.png' %}" alt="Devices Images" />
			</div>
			<div class="loginScreenBox">
				<div class="loginScreenBoxDialog">
					<div class="loginDialogHeaderGrid">
						<div class="loginDialogGridItem">
							<a id="switchToStudent" class="loginSwitchLinks isSelected" href="#">Student</a>
						</div>
						<div class="loginDialogGridItem">
							<a id="switchToFaculty" class="loginSwitchLinks" href="#">Faculty</a>
						</div>
					</div>
					<div class="loginContainerHandler">
						<div id="facultyLoginContainer" class="facultyLoginContainer">
							<form action="#" method="POST" class="col s12">
								{% csrf_token %}
								<div class="row">
									<div class="input-field col s12">
										{{form.userId}}
										<label for="userId" class="loginDialogLabel">User ID</label>
									</div>
								</div>
								<div class="row">
									<div class="input-field col s12">
										{{form.password}}
										<label for="password" class="loginDialogLabel">Password</label>
									</div>
								</div>
								<div class="row">
									<button
										class="btn black col s12 waves-effect waves-light loginBtn"
										type="submit"
										name="action"
									>
										Login
									</button>
								</div>
							</form>
						</div>
						<div id="studentLoginContainer" class="studentLoginContainer show">
							<form method="POST" class="col s12">
								{% csrf_token %}
								<div class="row">
									<div class="input-field col s12">
										{{form.studentNumber}}
										<label for="studentNumber" class="loginDialogLabel">Student Number</label>
									</div>
								</div>
								<div class="row">
									<div class="input-field col s12">
										{{form.userId}}
										<label for="userId" class="loginDialogLabel">User ID</label>
									</div>
								</div>
								<div class="row">
									<div class="input-field col s12">
										{{form.password}}
										<label for="password" class="loginDialogLabel">Password</label>
									</div>
								</div>
								<div class="row">
									<button
										class="btn black col s12 waves-effect waves-light loginBtn"
										type="submit"
										name="action"
									>
										Login
									</button>
								</div>
							</form>
						</div>
					</div>
					{% if messages %} {% for message in messages %}
					<div class="loginMessages">
						<p>{{message}}</p>
					</div>
					{% endfor %} {% endif %}
					<div class="loginScreenBoxBottom">
						<p>Don't have an account yet? <a href="{% url 'register' %}">Sign Up</a></p>
						<a href="#">Forgot your password</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/profilePage.html
{% extends 'base.html' %} {% load static %} {% block content %}

<h1>Hello World</h1>

{% endblock %}

accounts/templates/registerPage.html
{% extends 'base.html'%} {% load static %} {% block content %}
<div class="registerPage">
	<div class="registerPageWrapper">
		<div class="registerPageWrapperHeader">
			<h4>PD DOCUMENT ARCHIVER</h4>
		</div>
		<div class="registerPageWrapperMainScreen">
			<div class="registerPageWrapperTitle">
				<h4>Create a Student Account</h4>
				<p style="color: white">
					Already have an account? |
					<a
						style="color: white !important; text-decoration: underline; font-weight: 500"
						href="{% url 'login' %}"
						>Sign In</a
					>
				</p>
			</div>
			<div class="registerPageWrapperDialog">
				<div class="registerMainScreen">
					<form action="#" method="POST" class="col s12">
						{% csrf_token %}

						<div class="row">
							<div class="input-field col s5">
								{{form.firstName}}
								<label for="id_firstName" class="registerDialogLabel">First Name:</label>
							</div>
							<div class="input-field col s6" style="padding-left: 7em">
								{{form.email}}
								<label for="id_email" class="registerDialogLabel" style="padding-left: 5.5em"
									>Email Address:</label
								>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s5">
								{{form.middleName}}
								<label for="id_middleName" class="registerDialogLabel">Middle Name:</label>
							</div>
							<div class="input-field col s6" style="padding-left: 7em">
								{{form.studentNumber}}
								<label
									for="id_studentNumber"
									class="registerDialogLabel"
									style="padding-left: 5.5em"
									>Student Number</label
								>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s5">
								{{form.lastName}}
								<label for="id_lastName" class="registerDialogLabel">Last Name:</label>
							</div>
							<div class="input-field col s6 registerPasswordToolTip" style="padding-left: 7em">
								{{form.password1}}
								<label for="id_password1" class="registerDialogLabel" style="padding-left: 5.5em"
									>Password</label
								>
								<span class="registerPasswordToolTipText">
									Your password can’t be too similar to your other personal information.<br />
									Your password must contain at least 8 characters. <br />
									Your password can’t be a commonly used password. <br />
									Your password can’t be entirely numeric.
								</span>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s5">
								{{form.userId}}
								<label for="id_userId" class="registerDialogLabel">User ID:</label>
							</div>
							<div class="input-field col s6" style="padding-left: 7em">
								{{form.password2}}
								<label for="id_password2" class="registerDialogLabel" style="padding-left: 5.5em"
									>Confirm Password</label
								>
							</div>
						</div>
						<div class="registerMainScreenBottom">
							<button
								class="btn black col s12 waves-effect waves-light loginBtn"
								type="submit"
								name="action"
							>
								Create your account
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}